# Generated by Django 2.2.5 on 2019-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191008_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
