# Generated by Django 2.2.5 on 2019-10-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191008_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.IntegerField(choices=[(1, 'Starters'), (2, 'Main Course'), (3, 'Desserts'), (4, 'Berverages'), (5, 'Misc')], default=5),
        ),
        migrations.AddField(
            model_name='menu',
            name='veg',
            field=models.BooleanField(default=True),
        ),
    ]
