# Generated by Django 2.2.5 on 2019-10-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191008_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
